services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - APP_PORT=8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASS=adminn3t0p1a
      - DB_NAME=hierarchy_management
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminn3t0p1a
      MYSQL_ROOT_PASSWORD: n3t0p1a
      MYSQL_DATABASE: hierarchy_management
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  db_test:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminn3t0p1a
      MYSQL_ROOT_PASSWORD: n3t0p1a
      MYSQL_DATABASE: hierarchy_management_test
    volumes:
      - db_test_data:/var/lib/mysql
      - ./scripts_test:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: tester
    environment:
      - GIN_MODE=release
      - APP_PORT=8080
      - DB_HOST=db_test
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASS=adminn3t0p1a
      - DB_NAME=hierarchy_management_test
    depends_on:
      db_test:
        condition: service_healthy

volumes:
  db_data:
  db_test_data: