version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - APP_PORT=8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASS=adminn3t0p1a
      - DB_NAME=hierarchy_management
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminn3t0p1a
      MYSQL_ROOT_PASSWORD: n3t0p1a
      MYSQL_DATABASE: hierarchy_management
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  db_data: